version: "3.7"
services:
  php:
    build:
      args:
        user: shopper
        uid: 1000
      context: .
      dockerfile: docker/php/Dockerfile
    image: ${PROJECT_DIR_NAME}:${IMAGE_TAG}
    container_name: "${PROJECT_DIR_NAME}-php"
    ports:
      - 9000
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - "./app/:/var/www"
      - ./docker/php/www.pool.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.override.ini:ro
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mysql:${MYSQL_VERSION}
    container_name: ${PROJECT_DIR_NAME}-mysql
    restart: unless-stopped
    ports:
      - 33060:3306
    hostname: ${PROJECT_DIR_NAME}-db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      SERVICE_TAGS: ${APP_ENV}-db
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - app_db

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_DIR_NAME}-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./app/:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./var/logs/nginx:/var/log/nginx:consistent
    networks:
      - app_network
    depends_on:
      - db
      - php

networks:
  app_network:
    driver: bridge
  app_db:
    driver: bridge
